# split panes using \ and -
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
unbind '"'
unbind '%'

# open new windows in home directory
bind c new-window -c "#{pane_current_path}"

# remap prefix from 'C-b' to 'C-a'
#set -g prefix C-a
#unbind C-b
#bind C-a send-prefix

# switch panes without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-[ select-pane -t -1
bind -n M-] select-pane -t +1
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch windows without prefix
bind -n M-, select-window -t -1
bind -n M-. select-window -t +1

# Synchronize panes
# bind -n C-x setw synchronize-panes  # nice, but maybe bugged, pane freezes after using this

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# don't rename windows automatically
set-option -g allow-rename off

# Change inactive window color: 
set -g window-status-style bg=yellow

# Change active window color
set -g window-status-current-style bg=red,fg=white

# Change border color of all panes
set -g pane-border-style "fg=grey"

# Change active pane border color hightlight
set -g pane-active-border-style "fg=grey, bg=green"

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
set -g pane-base-index 1

# Get rid of delay
set -s escape-time 0

# Set history file
# set -g history-file ~/.tmux_history

