# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# remap prefix from 'C-b' to 'C-a'
#set -g prefix C-a
#unbind C-b
#bind C-a send-prefix

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-[ select-pane -t -1
bind -n M-] select-pane -t +1
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# don't rename windows automatically
set-option -g allow-rename off

# Change inactive window color: 
set -g window-status-style bg=yellow

# Change active window color
set -g window-status-current-style bg=red,fg=white

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
set -g pane-base-index 1

# Get rid of delay
set -s escape-time 0
