#!/usr/bin/bash

if [ $HOSTNAME == "macinArch" ]; then
    # set i3 configuration file
    sed -n '/{{WORKSPACE_SETUP}}/!{p;d;}; r /home/cjordan/configs/i3/macinArch/workspaces' /home/cjordan/configs/i3/i3.conf |\
    sed 's|{{SET_MOD_KEY}}|set \$mod mod1|g' |\
    sed 's|{{MONITOR_SETUP}}||g' \
    >| ~/.config/i3/config

    # set keyboard layout
    setxkbmap -model mac-us -layout us -option caps:swapescape

    # set resolution
    xrandr --output eDP-1 --primary --mode 1600x900

    # set bg image
    feh --bg-scale "/usr/share/backgrounds/leaf-bg.png"
    
    # dim the screen 
    xrandr --output eDP-1 --brightness 0.9
fi

if [ $HOSTNAME == "intelArch" ]; then
    # set i3 configuration file
    sed -n '/{{WORKSPACE_SETUP}}/!{p;d;}; r /home/cjordan/configs/i3/intelArch/workspaces' /home/cjordan/configs/i3/i3.conf |\
    sed 's|{{SET_MOD_KEY}}|set \$mod mod1|g' \
    >| ~/.config/i3/config

    # set keyboard layout
    setxkbmap -model us -layout us -option caps:swapescape

    # set resolution
#     xrandr --output eDP-1 --primary --mode 1920x1200

    # set bg image
    feh --bg-scale "/usr/share/backgrounds/leaf-bg.png"
fi
