#!/usr/bin/bash

if [ $HOSTNAME == "mac" ]; then
  # set external flag
  xrandr | grep -q "HDMI-1 connected" &&  xConn=true || xConn=false

  # set resolution
  xrandr --output eDP-1 --primary --mode 1600x900
  [[ $xConn == "true" ]] && xrandr --output HDMI-1 --auto --scale 1x1 --mode 1920x1080 --right-of eDP-1

  # set bg image
  feh --bg-scale "/usr/share/backgrounds/leaf-bg.png"

  # dim the screen 
  xrandr --output eDP-1 --brightness 1.0
fi

if [ $HOSTNAME == "nuc" ]; then
  # set resolution
  # xrandr --output eDP-1 --primary --mode 1920x1200

  # set bg image
  feh --bg-scale "/usr/share/backgrounds/leaf-bg.png"
fi

# set keyboard layout
setxkbmap -model us -layout us -option caps:swapescape
