- name: sudo setup
  hosts: localhost
  remote_user: cjordan
  become_method: sudo
  vars:
    host_user_home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    src: "{{ host_user_home }}/configs/system/backgrounds"
    dest: "/usr/share/backgrounds"
  tasks:
    - name: sync backgrounds directory
      become: yes
      ansible.posix.synchronize:
        src: "{{ src }}/"
        dest: "{{ dest }}/"
        mode: push
        archive: yes
        rsync_opts:
          - "--chown=root:root"
          - "--delete"

