- name: dunst config
  hosts: localhost
  gather_facts: yes
  remote_user: cjordan
  become: no
  vars_files: 
    - vars.yml
  vars:
    config_item: "dunst"
    src: "{{ dunst_config_src }}"
    dest: "{{ dunst_config_dest }}"
  tasks:
    - name: ensure destination path exists
      ansible.builtin.file:
        path: "{{ dest }}"
        state: directory
    - name: hard link config file
      ansible.builtin.file:
        src: "{{ src }}/dunstrc"
        dest: "{{ dest }}/dunstrc"
        state: hard
        force: true
