- name: gtk
  hosts: localhost
  gather_facts: yes
  remote_user: cjordan
  become: no
  vars_files: 
    - vars.yml
  vars:
    src: "{{ gtk3_config_src }}"
    dest: "{{ gtk3_config_dest }}"
  tasks:
    - name: sync directory
      ansible.posix.synchronize:
        src: "{{ src }}/"
        dest: "{{ dest }}"
        mode: push
        archive: yes
        rsync_opts:
          - "--delete"

    - name: find all config files recursively
      ansible.builtin.find:
        paths: "{{ src }}"
        patterns: "*"
        file_type: file
        recurse: yes
      register: all_files

    - name: ensure subdirectories exist at destination
      ansible.builtin.file:
        path: "{{ dest }}/{{ item.path | dirname | relpath(src) }}"
        state: directory
      loop: "{{ all_files.files }}"
      loop_control:
        label: "{{ item.path | dirname | relpath(src) }}"

    - name: hard link all config files
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ dest }}/{{ item.path | relpath(src) }}"
        state: hard
        force: true
      loop: "{{ all_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
