- name: Install initial packages
  hosts: localhost
  remote_user: cjordan
  become_user: root
  become: yes
  tasks:
    - name: Upgrade 
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install
      ansible.builtin.dnf:
        name:
          - vim
          - nvim
          - git
          - tmux
          - alacritty
          - thunderbird
          - npm
          - pnpm
          - cmake
          - just
          - make
          - clang
