### Init
- import_playbook: install-packages.yml

### Window Manager
- import_playbook: sway.yml

### Display Manager
- import_playbook: sddm-config.yml

### Window Switcher
- import_playbook: rofi-config.yml

### Status Bar
- import_playbook: waybar-config.yml

### Environment
- import_playbook: sudo-setup.yml
- import_playbook: env-config-root.yml
- import_playbook: env-config-user.yml
- import_playbook: terminal-config.yml

### Editors
- import_playbook: nvim-config.yml
- import_playbook: vim-config.yml
- import_playbook: zed-config.yml

### Misc
- import_playbook: backgrounds.yml
- import_playbook: git-config.yml
- import_playbook: dunst-config.yml
- import_playbook: gtk-config.yml
