- name: nvim config
  hosts: localhost
  remote_user: "{{ nvim_user | default('cjordan') }}"
  vars_files:
    - vars.yml
  vars:
    config_item: "nvim"
    src: "{{ nvim_config_src }}"
    dest: "{{ nvim_config_dest }}"
  tasks:
    - name: find all {{ config_item }} config files
      ansible.builtin.find:
        paths: "{{ src }}"
        file_type: file
        recurse: yes
      register: config_files

    - name: create {{ config_item }} config directory
      ansible.builtin.file:
        path: "{{ dest }}"
        state: directory

    - name: create {{ config_item }} sub directories 
      ansible.builtin.file:
        path: "{{ dest }}/{{ (item.path | regex_replace('^' + src + '/?', '')) | dirname }}"
        state: directory
      loop: "{{ config_files.files }}"
      when: (item.path | regex_replace('^' + src + '/?', '')) | dirname != '.'

    - name: hard link config files
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ dest }}/{{ item.path | regex_replace('^' + src + '/?', '') }}"
        state: hard
        force: true
      loop: "{{ config_files.files }}"

    - name: create templates directory
      ansible.builtin.file:
        path: "{{ dest }}/templates"
        state: directory

    - name: find template files
      ansible.builtin.find:
        paths: "{{ editor_template_src }}"
        file_type: file
      register: template_files

    - name: hard link template files
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ dest }}/templates/{{ item.path | basename }}"
        state: hard
        force: true
      loop: "{{ template_files.files }}"

