- name: nvim config
  hosts: localhost
  remote_user: "{{ nvim_user | default('cjordan') }}"
  vars_files:
    - vars.yml
  tasks:
    - name: Find all nvim config files
      ansible.builtin.find:
        paths: "{{ nvim_config_src }}"
        file_type: file
        recurse: yes
      register: nvim_files

    - name: Create nvim config directory
      ansible.builtin.file:
        path: "{{ nvim_config_dest }}"
        state: directory

    - name: Create nvim sub directories 
      ansible.builtin.file:
        path: "{{ nvim_config_dest }}/{{ (item.path | regex_replace('^' + nvim_config_src + '/?', '')) | dirname }}"
        state: directory
      loop: "{{ nvim_files.files }}"
      when: (item.path | regex_replace('^' + nvim_config_src + '/?', '')) | dirname != '.'

    - name: Hard link config files
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ nvim_config_dest }}/{{ item.path | regex_replace('^' + nvim_config_src + '/?', '') }}"
        state: hard
        force: true
      loop: "{{ nvim_files.files }}"

    - name: create templates directory
      ansible.builtin.file:
        path: "{{ nvim_config_dest }}/templates"
        state: directory

    - name: find template files
      ansible.builtin.find:
        paths: "{{ editor_template_src }}"
        file_type: file
      register: template_files

    - name: hard link template files
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ nvim_config_dest }}/templates/{{ item.path | basename }}"
        state: hard
        force: true
      loop: "{{ template_files.files }}"

