- name: Workmux configuration
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yml
  tasks:
    - name: Create Workmux config directory
      ansible.builtin.file:
        path: "{{ workmux_dest | dirname }}"
        state: directory

    - name: Hard link Workmux config
      ansible.builtin.file:
        src: "{{ workmux_src }}"
        dest: "{{ workmux_dest }}"
        state: hard
        force: true
